aws:
  region: "us-east-2"
  username: "app-user"
  access_key_id: "AKIAZX4PBR7ZB6QPZFCQ"
  secret_access_key: "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"
  s3:
    bucket_name: "lakelab-test-bucket"


