spring:
  profiles:
    active: "local"
  main:
    banner-mode: "off"

server.error.include-stacktrace: "never"

#aws:
#  region: "us-east-2"
#  username: "app-user"
#  access_key_id: ""
#  secret_access_key: ""
#  s3:
#    bucket_name: "lakelab-test-bucket"